config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  get "sessions/new"

  
  resources :users
  resources :sessions, :only => [:new,:create,:destroy]
  resources :microposts, :only=> [:create,:destroy]
  resources :relationships, :only => [:create,:destroy]
  
  

  match '/contact', :to => 'pages#contact'
  
  match '/about',   :to => 'pages#about'
  
  match '/help',    :to => 'pages#help'
  
  match '/contact', :to => 'pages#contact'
  
  match '/signup', :to => 'users#new'
  
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  

  root :to => 'pages#home'

end

app/views/pages/about.html.erb
<h1>Sample App</h1>
<p>
  This is the about page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/pages/contact.html.erb
<h1>Sample App</h1>
<p>
  This is the contact page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/pages/help.html.erb
<h1>Sample App</h1>
<p>
This is the is the help page 	
</p>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front"summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">What's up?</h1>
        <%= render 'shared/micropost_form' %>
        <%= render 'shared/feed' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
        <%= render 'shared/stats' %>
      </td>
    </tr>
  </table>

  <% else %>
<h1>Twitter-Tastic!</h1>
<p>
  <table>
    <tr>
      <td>
      <%= gravatar_for_email "bence.magyar@gmail.com", "bence", :size=> 100 %>
      </td>
      <td>
        Welcome to Twitter-Tastic:
        A little twitter clone developed by 
        <a href="http://linkedin.com/in/bencemagyar">Bence</a>
        in order to gain some Ruby/Rails chops.  The wise sage of 
        <a href="http://railstutorial.org/">Michael Hartl</a> was leveraged for this development effort.
      </td>
    </tr>
    <tr>
      <td>
		  	<%= render 'sessions/signin' %>
				<p>New user?  <%= link_to "Sign up now!", signup_path %></p>
			</td>
    </tr>
    
  </table>
    
</p>

<% end %>