config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  get "sessions/new"

  
  resources :users
  resources :sessions, :only => [:new,:create,:destroy]
  resources :microposts, :only=> [:create,:destroy]
  resources :relationships, :only => [:create,:destroy]
  
  

  match '/contact', :to => 'pages#contact'
  
  match '/about',   :to => 'pages#about'
  
  match '/help',    :to => 'pages#help'
  
  match '/contact', :to => 'pages#contact'
  
  match '/signup', :to => 'users#new'
  
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
	  <li><%= link_to "Contact", contact_path %></li>
	  <li><a href="http://www.railstutorial.org/">News</a></li>
 	  <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
	</ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("followme2.jpg", :size => "120x100", :alt => "Sample App", :class => "Round")%>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
    <li><%= link_to "Home", root_path %></li>
	  <li><%= link_to "Help", help_path %></li>
 	  <% if signed_in? %>
 	  <li><%= link_to "Users", users_path %></li>
 	  <li><%= link_to "Profile", current_user %></li>
 	  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
 	  <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
 	  <% else %>
	  <li><%= link_to "Sign in", signin_path %></li>
	  <% end %>
	</ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<%= stylesheet_link_tag 'blueprint/screen', :media=> 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media=> 'print' %>

<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media=> 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    
    <!-- this is the partial to the _stylesheet -->
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
    	
  </head>
  <body>
  	<div class="container">
  	  <%= render 'layouts/header' %>
  	  <section class="round">
  	    <% flash.each do |key,value| %>
  	    <div class="flash <%= key %>"><%= value %></div>
  	    <% end %>
  	    <%= yield %>		
  	  </section>
  	  <%= render 'layouts/footer'%>
  	  <%= debug(params) if Rails.env.development? %>
  	</div>
  </body>
</html>